/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bengkel;
//import package Koneksi.Koneksi;
import Koneksi.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login Login;
    public Gudang FormGudang;
    public Kasir FormKasir;
    public Pemilik FormPemilik;
    public Mekanik FormMekanik;
    Koneksi db = new Koneksi();
    public Connection con;
    public Statement stt; 
    
    private Profile Profile;
    
    public Login() {
        initComponents();
        KoneksiDataBase();
        KosongkanTabelSementara();
        KosongkanTabelSementaraService();
        KosongkanTblSementaraService();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        JB_L_Batal = new javax.swing.JButton();
        JB_L_Keluar = new javax.swing.JButton();
        JB_L_TesKoneksi = new javax.swing.JButton();
        JB_L_Login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JP_L_Password = new javax.swing.JPasswordField();
        JT_L_Username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(195, 182, 240));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        JB_L_Batal.setText("Batal");
        JB_L_Batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_L_BatalActionPerformed(evt);
            }
        });

        JB_L_Keluar.setText("Keluar");
        JB_L_Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_L_KeluarActionPerformed(evt);
            }
        });

        JB_L_TesKoneksi.setText("Tes Koneksi");
        JB_L_TesKoneksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_L_TesKoneksiActionPerformed(evt);
            }
        });

        JB_L_Login.setText("Login");
        JB_L_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_L_LoginActionPerformed(evt);
            }
        });

        jLabel1.setText("Username");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bengkel/Z - .z1.png"))); // NOI18N

        JT_L_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_L_UsernameActionPerformed(evt);
            }
        });

        jLabel2.setText("Password");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel4.setText("DEDI MOTOR");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JT_L_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addComponent(JB_L_Login))
                                        .addComponent(JB_L_Batal))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(JB_L_TesKoneksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(JB_L_Keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(JP_L_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 15, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JT_L_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JP_L_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_L_Login)
                    .addComponent(JB_L_Keluar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_L_Batal)
                    .addComponent(JB_L_TesKoneksi))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void JB_L_KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_L_KeluarActionPerformed
        int selectedOption = JOptionPane.showConfirmDialog(null,
         "Apakah anda akan menutup Aplikasi?", "Tutup Aplikasi", JOptionPane.YES_NO_OPTION);
         if (selectedOption == JOptionPane.YES_OPTION) {
         System.exit(0);
         }
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_L_KeluarActionPerformed

    private void JB_L_TesKoneksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_L_TesKoneksiActionPerformed
        db.TesKoneksi();
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_L_TesKoneksiActionPerformed

    @SuppressWarnings("static-access")
    private void JB_L_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_L_LoginActionPerformed
        String level = "";
        try {
            String sql;
            sql = "Select * from user where id_user = '"+JT_L_Username.getText()+"' and password_user = '"+String.valueOf(JP_L_Password.getPassword())+"'";
            ResultSet rss = stt.executeQuery(sql);
            while (rss.next()){
                level = rss.getString(6);   
                }
            if(level.equals("")){
                JOptionPane.showMessageDialog(null, "ID atau password yang anda masukan Salah!!");
            }
            else{
                switch (level) {
                    case "pemilik":
                        FormPemilik = new Pemilik();
                        FormPemilik.ID_User.setText(Login.JT_L_Username.getText());
                        FormPemilik.setVisible(true);
                        this.dispose();
                    break;
                    case "gudang":
                        FormGudang = new Gudang();
                        FormGudang.ID_User.setText(Login.JT_L_Username.getText());
                        FormGudang.setVisible(true);
                        this.dispose();
                    break;
                    case "kasir":
                        FormKasir = new Kasir();
                        FormKasir.ID_User.setText(Login.JT_L_Username.getText());
                        FormKasir.setVisible(true);
                        this.dispose();
                    break;
                    case "mekanik":
                        FormMekanik = new Mekanik();
                        FormMekanik.ID_User.setText(Login.JT_L_Username.getText());
                        FormMekanik.setVisible(true);
                        this.dispose();
                    break;
                    default:
                        JOptionPane.showMessageDialog(null, "Terjadi Kesalahan");
                    }
                } 
                
             } catch (Exception e){  
                JOptionPane.showMessageDialog(null,e);
           }
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_L_LoginActionPerformed

    private void JB_L_BatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_L_BatalActionPerformed
        JT_L_Username.setText("");
        JP_L_Password.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_L_BatalActionPerformed

    private void JT_L_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_L_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_L_UsernameActionPerformed

    public void KoneksiDataBase()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_bengkel?zeroDateTimeBehavior=convertToNull","root","");
            stt = con.createStatement();
            } catch (Exception e){
            JOptionPane.showMessageDialog(null,"DATABASE tidak terhubung!");
            }
    }
    
    void KosongkanTblSementaraService()
    {
        try{
            Statement stmr;
            stmr=con.createStatement();
            stmr.executeUpdate("truncate table updateBarangservice");
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    public void KosongkanTabelSementara()
    {
        KosongkanTabelSFakturPenjualan();
        KosongkanTabelSTransJual();
    }
    
    public void KosongkanTabelSementaraService()
    {
        KosongkanTabelSFakturPS();
        KosongkanTabelSRincianPS();
    }
    
    void KosongkanTabelSFakturPenjualan()
    {
        try{
            Statement stmr;
            stmr=con.createStatement();
            stmr.executeUpdate("truncate table s_faktur_penjualan_barang");
        }catch(Exception e){
            e.printStackTrace();        
        }
    }
    
    void KosongkanTabelSTransJual()
    {
        try{
            Statement stmr;
            stmr=con.createStatement();
            stmr.executeUpdate("truncate table s_trans_jual_barang");
        }catch(Exception e){
            e.printStackTrace();        
        }
    }
    
    void KosongkanTabelSFakturPS()
    {
        try{
            Statement stmr;
            stmr=con.createStatement();
            stmr.executeUpdate("truncate table s_faktur_pembayaran_service");
        }catch(Exception e){
            e.printStackTrace();        
        }
    }
    
    
    void KosongkanTabelSRincianPS()
    {
        try{
            Statement stmr;
            stmr=con.createStatement();
            stmr.executeUpdate("truncate table rincian_pembayaran_service");
        }catch(Exception e){
            e.printStackTrace();        
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login mn=new Login();
                mn.setExtendedState(JFrame.MAXIMIZED_BOTH);
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_L_Batal;
    private javax.swing.JButton JB_L_Keluar;
    private javax.swing.JButton JB_L_Login;
    private javax.swing.JButton JB_L_TesKoneksi;
    private javax.swing.JPasswordField JP_L_Password;
    public static javax.swing.JTextField JT_L_Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
