/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bengkel;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.lang.String.format;
import static java.lang.String.format;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import static jdk.nashorn.api.scripting.ScriptUtils.format;


/**
 *
 * @author Lenovo
 */
public class Pemilik extends javax.swing.JFrame {

    /**
     * Creates new form Pemilik
     */
    
    private Profile Profile;
    private Bantuan Bantuan;
    private Tentang Tentang;
    ResultSet rsmekanik=null;
    public Connection con=null;
    public Statement stt;
    DefaultTableModel tabModel;
    String tanggal_lahir;
    String tanggal_lahir1;
    
    public Pemilik() {
        initComponents();
        
        KoneksiDataBase();
        
        ActionListener aksi = new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                tampilNama();
        }
        
        };
        new Timer(150, aksi).start();
        Tanggal();
        tampilDataU();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JB_P_Keluar = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        Nama_User = new javax.swing.JLabel();
        ID_User = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        Tanggal = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        User = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTB_P_U_User = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        JB_P_U_Tambah = new javax.swing.JButton();
        JT_P_U_Nama_User = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTA_P_U_Alamat = new javax.swing.JTextArea();
        JD_P_U_Tanggal_Lahir = new com.toedter.calendar.JDateChooser();
        JB_P_U_Edit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        JB_P_U_Segarkan = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        JB_P_U_Hapus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        JT_P_U_Tempat_lahir = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        JP_P_U_Password_User = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        JB_P_U_Bersihkan = new javax.swing.JButton();
        JC_P_U_Level = new javax.swing.JComboBox();
        JT_P_U_Telepon = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        JT_P_U_ID_User = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Daftar_Barang = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTB_P_DB_Barang = new javax.swing.JTable();
        JT_P_DB_Cari = new javax.swing.JTextField();
        JB_P_DB_Cari = new javax.swing.JButton();
        Transaksi = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        JTB_P_T_Transaksi = new javax.swing.JTable();
        JT_P_T_Cari = new javax.swing.JTextField();
        JB_P_T_Cari = new javax.swing.JButton();
        Service = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        JB_P_DS_Cari = new javax.swing.JButton();
        JT_P_DS_Cari = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        JTB_P_DS_Daftar_service = new javax.swing.JTable();
        Transaksi_service = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        JTB_P_DTS_Transaksi_Service = new javax.swing.JTable();
        JB_P_DTS_Cari = new javax.swing.JButton();
        JT_P_DTS_Cari = new javax.swing.JTextField();
        Daftar_supplier = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        JTB_P_DSu_Daftar_Supplier = new javax.swing.JTable();
        jTextField7 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        Daftar_Kategori_Barang = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        JTB_P_DKB_Kategori_Barangi = new javax.swing.JTable();
        JT_P_DKB_Cari = new javax.swing.JTextField();
        JB_P_DKB_Cari = new javax.swing.JButton();
        Laporan = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));
        setUndecorated(true);

        jLabel1.setText("PEMILIK");

        JB_P_Keluar.setText("Keluar");
        JB_P_Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_P_KeluarActionPerformed(evt);
            }
        });

        jButton18.setText("Bantuan");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setText("Tentang");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jLabel11.setText("Nama :");

        jButton3.setText("Profile");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Nama_User.setText("Nama User");

        ID_User.setText("ID User");

        jButton4.setText("Log Out");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Tanggal.setText("Tanggal");

        jLabel10.setText("ID User :");

        User.setBackground(new java.awt.Color(204, 255, 255));

        JTB_P_U_User.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTB_P_U_User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTB_P_U_UserMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(JTB_P_U_User);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        JB_P_U_Tambah.setText("Tambah");
        JB_P_U_Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_P_U_TambahActionPerformed(evt);
            }
        });

        jLabel4.setText("Level");

        JTA_P_U_Alamat.setColumns(20);
        JTA_P_U_Alamat.setRows(5);
        jScrollPane1.setViewportView(JTA_P_U_Alamat);

        JD_P_U_Tanggal_Lahir.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                JD_P_U_Tanggal_LahirPropertyChange(evt);
            }
        });

        JB_P_U_Edit.setText("Edit");
        JB_P_U_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_P_U_EditActionPerformed(evt);
            }
        });

        jLabel6.setText("Alamat");

        JB_P_U_Segarkan.setText("Segarkan");
        JB_P_U_Segarkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_P_U_SegarkanActionPerformed(evt);
            }
        });

        jLabel8.setText("Tempat Lahir");

        JB_P_U_Hapus.setText("Hapus");
        JB_P_U_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_P_U_HapusActionPerformed(evt);
            }
        });

        jLabel2.setText("ID User");

        jLabel9.setText("Tanggal Lahir");

        jLabel3.setText("Nama User");

        JB_P_U_Bersihkan.setText("Bersihkan");
        JB_P_U_Bersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_P_U_BersihkanActionPerformed(evt);
            }
        });

        JC_P_U_Level.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "pemilik", "gudang", "kasir", "mekanik" }));

        jLabel7.setText("Password");

        jLabel5.setText("Telepon");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JT_P_U_Nama_User)
                            .addComponent(JT_P_U_ID_User)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JB_P_U_Bersihkan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JB_P_U_Segarkan))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JC_P_U_Level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JT_P_U_Telepon, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JB_P_U_Tambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JB_P_U_Edit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JB_P_U_Hapus)))
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JD_P_U_Tanggal_Lahir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JP_P_U_Password_User)
                            .addComponent(JT_P_U_Tempat_lahir))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JT_P_U_ID_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JT_P_U_Nama_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JP_P_U_Password_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(JT_P_U_Tempat_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(JD_P_U_Tanggal_Lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JC_P_U_Level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JT_P_U_Telepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_P_U_Tambah)
                    .addComponent(JB_P_U_Edit)
                    .addComponent(JB_P_U_Hapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_P_U_Bersihkan)
                    .addComponent(JB_P_U_Segarkan))
                .addContainerGap())
        );

        javax.swing.GroupLayout UserLayout = new javax.swing.GroupLayout(User);
        User.setLayout(UserLayout);
        UserLayout.setHorizontalGroup(
            UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        UserLayout.setVerticalGroup(
            UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("User", User);

        Daftar_Barang.setBackground(new java.awt.Color(204, 255, 255));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        JTB_P_DB_Barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(JTB_P_DB_Barang);

        JB_P_DB_Cari.setText("Cari");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(JT_P_DB_Cari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JB_P_DB_Cari)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JT_P_DB_Cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_P_DB_Cari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Daftar_BarangLayout = new javax.swing.GroupLayout(Daftar_Barang);
        Daftar_Barang.setLayout(Daftar_BarangLayout);
        Daftar_BarangLayout.setHorizontalGroup(
            Daftar_BarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Daftar_BarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Daftar_BarangLayout.setVerticalGroup(
            Daftar_BarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Daftar_BarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Daftar Barang", Daftar_Barang);

        Transaksi.setBackground(new java.awt.Color(204, 255, 255));
        Transaksi.setForeground(new java.awt.Color(204, 255, 255));

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        JTB_P_T_Transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(JTB_P_T_Transaksi);

        JB_P_T_Cari.setText("Cari");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(JT_P_T_Cari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JB_P_T_Cari)
                        .addGap(20, 20, 20)))
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JT_P_T_Cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_P_T_Cari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TransaksiLayout = new javax.swing.GroupLayout(Transaksi);
        Transaksi.setLayout(TransaksiLayout);
        TransaksiLayout.setHorizontalGroup(
            TransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        TransaksiLayout.setVerticalGroup(
            TransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Transaksi", Transaksi);

        Service.setBackground(new java.awt.Color(204, 255, 255));
        Service.setForeground(new java.awt.Color(204, 255, 255));

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));

        JB_P_DS_Cari.setText("Cari");

        JTB_P_DS_Daftar_service.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane7.setViewportView(JTB_P_DS_Daftar_service);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(JT_P_DS_Cari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JB_P_DS_Cari)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JT_P_DS_Cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_P_DS_Cari))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout ServiceLayout = new javax.swing.GroupLayout(Service);
        Service.setLayout(ServiceLayout);
        ServiceLayout.setHorizontalGroup(
            ServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ServiceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ServiceLayout.setVerticalGroup(
            ServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ServiceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Service", Service);

        Transaksi_service.setBackground(new java.awt.Color(204, 255, 255));

        jPanel5.setBackground(new java.awt.Color(102, 204, 255));
        jPanel5.setForeground(new java.awt.Color(102, 204, 255));

        JTB_P_DTS_Transaksi_Service.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane8.setViewportView(JTB_P_DTS_Transaksi_Service);

        JB_P_DTS_Cari.setText("Cari");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(JT_P_DTS_Cari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JB_P_DTS_Cari)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JT_P_DTS_Cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_P_DTS_Cari))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Transaksi_serviceLayout = new javax.swing.GroupLayout(Transaksi_service);
        Transaksi_service.setLayout(Transaksi_serviceLayout);
        Transaksi_serviceLayout.setHorizontalGroup(
            Transaksi_serviceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Transaksi_serviceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Transaksi_serviceLayout.setVerticalGroup(
            Transaksi_serviceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Transaksi_serviceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Transaksi Service", Transaksi_service);

        Daftar_supplier.setBackground(new java.awt.Color(204, 255, 255));

        jPanel6.setBackground(new java.awt.Color(102, 204, 255));

        JTB_P_DSu_Daftar_Supplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(JTB_P_DSu_Daftar_Supplier);

        jButton8.setText("Cari");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jTextField7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Daftar_supplierLayout = new javax.swing.GroupLayout(Daftar_supplier);
        Daftar_supplier.setLayout(Daftar_supplierLayout);
        Daftar_supplierLayout.setHorizontalGroup(
            Daftar_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Daftar_supplierLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Daftar_supplierLayout.setVerticalGroup(
            Daftar_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Daftar_supplierLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Daftar Supplier", Daftar_supplier);

        Daftar_Kategori_Barang.setBackground(new java.awt.Color(204, 255, 255));

        jPanel7.setBackground(new java.awt.Color(153, 204, 255));

        JTB_P_DKB_Kategori_Barangi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(JTB_P_DKB_Kategori_Barangi);

        JB_P_DKB_Cari.setText("Cari");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(JT_P_DKB_Cari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JB_P_DKB_Cari)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JT_P_DKB_Cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_P_DKB_Cari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Daftar_Kategori_BarangLayout = new javax.swing.GroupLayout(Daftar_Kategori_Barang);
        Daftar_Kategori_Barang.setLayout(Daftar_Kategori_BarangLayout);
        Daftar_Kategori_BarangLayout.setHorizontalGroup(
            Daftar_Kategori_BarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Daftar_Kategori_BarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Daftar_Kategori_BarangLayout.setVerticalGroup(
            Daftar_Kategori_BarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Daftar_Kategori_BarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Daftar Kategori barang", Daftar_Kategori_Barang);

        Laporan.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout LaporanLayout = new javax.swing.GroupLayout(Laporan);
        Laporan.setLayout(LaporanLayout);
        LaporanLayout.setHorizontalGroup(
            LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 834, Short.MAX_VALUE)
        );
        LaporanLayout.setVerticalGroup(
            LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 523, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Laporan", Laporan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JB_P_Keluar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton19)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel10)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(ID_User)
                    .addGap(27, 27, 27)
                    .addComponent(jLabel11)
                    .addGap(18, 18, 18)
                    .addComponent(Nama_User)
                    .addGap(64, 64, 64)
                    .addComponent(jButton3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                    .addComponent(Tanggal)
                    .addGap(77, 77, 77)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JB_P_Keluar)
                        .addComponent(jButton18)
                        .addComponent(jButton19))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tanggal)
                            .addComponent(jLabel10)
                            .addComponent(ID_User)
                            .addComponent(jLabel11)
                            .addComponent(Nama_User))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4)))
                    .addContainerGap(598, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public void KoneksiDataBase()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_bengkel?zeroDateTimeBehavior=convertToNull","root","");
            stt = con.createStatement();
            } catch (Exception e){
            JOptionPane.showMessageDialog(null,"DATABASE tidak terhubung!");
            }
    }
    
    void tampilNama(){
        try{
            String id_user = ID_User.getText();
            Statement stm; 
            stm=con.createStatement();
            rsmekanik=stm.executeQuery("select * from user where id_user = '"+id_user+"'");
            while(rsmekanik.next()){
             Nama_User.setText(rsmekanik.getString("nama_user"));
             //Nama_User.setText(ID_User.getText());
            }
            //mengambil data            
        }catch(SQLException e){
        }
    }
    
    void Tanggal(){
        Date now = new Date();
        SimpleDateFormat simpleDateFormat = 
                new SimpleDateFormat("yyyy-MM-dd");
        String tgl = simpleDateFormat.format(now);
        Tanggal.setText(tgl);
    }
    
    void kosongkanFormUser(){
        JT_P_U_ID_User.setText("");
        JT_P_U_Nama_User.setText("");
        JP_P_U_Password_User.setText("");
        JT_P_U_Tempat_lahir.setText("");
        JC_P_U_Level.setSelectedItem("");
        JT_P_U_Telepon.setText("");
        JTA_P_U_Alamat.setText("");
    }
    
    void tampilDataU(){
        Object[] judul_kolom = {"ID USER","NAMA USER","TEMPAT LAHIR","TANGGAL LAHIR","ALAMAT","TELEPON","LEVEL"};
            tabModel=new DefaultTableModel(null,judul_kolom);
            JTB_P_U_User.setModel(tabModel);
        try{
            Statement stm; //buat stm
            stm=con.createStatement();
            tabModel.getDataVector().removeAllElements();
            rsmekanik=stm.executeQuery("select * from user");//mengambil data barang
            while(rsmekanik.next()){
                Object[] data={rsmekanik.getString("id_user"),                               
                               rsmekanik.getString("nama_user"),                               
                               rsmekanik.getString("tempat_lahir"),
                               rsmekanik.getString("tanggal_lahir"),                               
                               rsmekanik.getString("alamat"),                               
                               rsmekanik.getString("telepon"),
                               rsmekanik.getString("level"),
                };
                tabModel.addRow(data);
            }
        }catch(Exception e){
            e.printStackTrace();
                    
        }
    }
    
    void TambahUser()
    {
        if (JT_P_U_ID_User.getText().equals("") 
            || JT_P_U_Nama_User.getText().equals("") || JP_P_U_Password_User.getText().equals("") 
            || JT_P_U_Tempat_lahir.getText().equals("")
            || JT_P_U_Telepon.getText().equals("")|| JTA_P_U_Alamat.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Form Tidak Boleh Kosong");
        }else{
            try{
                Statement stm; //buat stm
                stm=con.createStatement();
                stm.executeUpdate("insert into user set id_user='"+JT_P_U_ID_User.getText()+"',"+
                    "nama_user='"+JT_P_U_Nama_User.getText()+"',"+
                    "password_user='"+String.valueOf(JP_P_U_Password_User.getPassword())+"',"+
                    "tempat_lahir='"+JT_P_U_Tempat_lahir.getText()+"',"+
                    "tanggal_lahir='"+tanggal_lahir+"',"+
                    "alamat='"+JTA_P_U_Alamat.getText()+"',"+
                    "telepon='"+JT_P_U_Telepon.getText()+"',"+
                    "level='"+JC_P_U_Level.getSelectedItem()+"'");
            }catch(Exception e){
                e.printStackTrace();
            }
        }
    }
    
    void tblKeForm() throws ParseException{
        JT_P_U_ID_User.setText(tabModel.getValueAt(JTB_P_U_User.getSelectedRow(),0)+"");
        JT_P_U_Nama_User.setText(tabModel.getValueAt(JTB_P_U_User.getSelectedRow(),1)+"");
        JT_P_U_Tempat_lahir.setText(tabModel.getValueAt(JTB_P_U_User.getSelectedRow(),2)+"");
        tanggal_lahir1=(tabModel.getValueAt(JTB_P_U_User.getSelectedRow(),3)+"");
        SimpleDateFormat Format=new SimpleDateFormat("yyyy-MM-dd");
        Date date = Format.parse(tanggal_lahir1);
        JD_P_U_Tanggal_Lahir.setDate(date);
        JTA_P_U_Alamat.setText(tabModel.getValueAt(JTB_P_U_User.getSelectedRow(),4)+"");
        JT_P_U_Telepon.setText(tabModel.getValueAt(JTB_P_U_User.getSelectedRow(),5)+"");
        JC_P_U_Level.setSelectedItem(tabModel.getValueAt(JTB_P_U_User.getSelectedRow(),6)+"");
    }
    
    void EditUser()
    {
        if (JT_P_U_ID_User.getText().equals("")  
            || JT_P_U_Nama_User.getText().equals("") || JP_P_U_Password_User.getText().equals("") 
            || JT_P_U_Tempat_lahir.getText().equals("") || JT_P_U_Telepon.getText().equals("") 
            || JTA_P_U_Alamat.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Form Tidak Boleh Kosong");
        }else{
        try{
            Statement stm; //buat stm
            stm=con.createStatement();
            stm.executeUpdate("update user set id_user='"+JT_P_U_ID_User.getText()+"',"+
                "password_user='"+String.valueOf(JP_P_U_Password_User.getPassword())+"',"+
                "nama_user='"+JT_P_U_Nama_User.getText()+"',"+
                "tempat_lahir='"+JT_P_U_Tempat_lahir.getText()+"',"+
                "tanggal_lahir='"+tanggal_lahir+"',"+
                "alamat='"+JTA_P_U_Alamat.getText()+"',"+
                "telepon='"+JT_P_U_Telepon.getText()+"',"+
                "level='"+JC_P_U_Level.getSelectedItem()+"'"
                + "where id_user like '%"+JT_P_U_ID_User.getText()+"%'");
        }catch(Exception e){
            e.printStackTrace();

        }
        }
    }
    
    void HapusUser()
    {
        try{
            Statement stm; //buat stm
            stm=con.createStatement();
            stm.executeUpdate("delete from user where id_user='"+JT_P_U_ID_User.getText()+"'");
        }catch(Exception e){
            e.printStackTrace();

        }
    }
    
    private void JB_P_KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_P_KeluarActionPerformed
        // TODO add your handling code here:
        int selectedOption = JOptionPane.showConfirmDialog(null,
         "Apakah anda akan menutup Aplikasi?", "Tutup Aplikasi", JOptionPane.YES_NO_OPTION);
         if (selectedOption == JOptionPane.YES_OPTION) {
         System.exit(0);
         }
    }//GEN-LAST:event_JB_P_KeluarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Profile = new Profile();
        new Profile().setVisible(true);
        Profile.ID_User.setText(Login.JT_L_Username.getText());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        new Bantuan().setVisible(true);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        new Tentang().setVisible(true);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void JB_P_U_TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_P_U_TambahActionPerformed
        // TODO add your handling code here:
        TambahUser();
        tampilDataU();
        kosongkanFormUser();
    }//GEN-LAST:event_JB_P_U_TambahActionPerformed

    private void JB_P_U_BersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_P_U_BersihkanActionPerformed
        // TODO add your handling code here:
        kosongkanFormUser();
    }//GEN-LAST:event_JB_P_U_BersihkanActionPerformed

    private void JD_P_U_Tanggal_LahirPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_JD_P_U_Tanggal_LahirPropertyChange
        // TODO add your handling code here:
        if (JD_P_U_Tanggal_Lahir.getDate()!=null){
        SimpleDateFormat Format=new SimpleDateFormat("yyyy-MM-dd");
        tanggal_lahir=Format.format(JD_P_U_Tanggal_Lahir.getDate());
        }
    }//GEN-LAST:event_JD_P_U_Tanggal_LahirPropertyChange

    private void JB_P_U_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_P_U_EditActionPerformed
        // TODO add your handling code here:
        EditUser();
        tampilDataU();
        kosongkanFormUser();
    }//GEN-LAST:event_JB_P_U_EditActionPerformed

    private void JTB_P_U_UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTB_P_U_UserMouseClicked
        try {
            // TODO add your handling code here:
            tblKeForm();
        } catch (ParseException ex) {
            Logger.getLogger(Pemilik.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JTB_P_U_UserMouseClicked

    private void JB_P_U_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_P_U_HapusActionPerformed
        // TODO add your handling code here:
        HapusUser();
        tampilDataU();
        kosongkanFormUser();
    }//GEN-LAST:event_JB_P_U_HapusActionPerformed

    private void JB_P_U_SegarkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_P_U_SegarkanActionPerformed
        // TODO add your handling code here:
        tampilDataU();
    }//GEN-LAST:event_JB_P_U_SegarkanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pemilik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pemilik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pemilik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pemilik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Pemilik mn=new Pemilik();
                mn.setExtendedState(JFrame.MAXIMIZED_BOTH);
                mn.setVisible(true);
                //new Pemilik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Daftar_Barang;
    private javax.swing.JPanel Daftar_Kategori_Barang;
    private javax.swing.JPanel Daftar_supplier;
    public static javax.swing.JLabel ID_User;
    private javax.swing.JButton JB_P_DB_Cari;
    private javax.swing.JButton JB_P_DKB_Cari;
    private javax.swing.JButton JB_P_DS_Cari;
    private javax.swing.JButton JB_P_DTS_Cari;
    private javax.swing.JButton JB_P_Keluar;
    private javax.swing.JButton JB_P_T_Cari;
    private javax.swing.JButton JB_P_U_Bersihkan;
    private javax.swing.JButton JB_P_U_Edit;
    private javax.swing.JButton JB_P_U_Hapus;
    private javax.swing.JButton JB_P_U_Segarkan;
    private javax.swing.JButton JB_P_U_Tambah;
    private javax.swing.JComboBox JC_P_U_Level;
    private com.toedter.calendar.JDateChooser JD_P_U_Tanggal_Lahir;
    private javax.swing.JPasswordField JP_P_U_Password_User;
    private javax.swing.JTextArea JTA_P_U_Alamat;
    private javax.swing.JTable JTB_P_DB_Barang;
    private javax.swing.JTable JTB_P_DKB_Kategori_Barangi;
    private javax.swing.JTable JTB_P_DS_Daftar_service;
    private javax.swing.JTable JTB_P_DSu_Daftar_Supplier;
    private javax.swing.JTable JTB_P_DTS_Transaksi_Service;
    private javax.swing.JTable JTB_P_T_Transaksi;
    private javax.swing.JTable JTB_P_U_User;
    private javax.swing.JTextField JT_P_DB_Cari;
    private javax.swing.JTextField JT_P_DKB_Cari;
    private javax.swing.JTextField JT_P_DS_Cari;
    private javax.swing.JTextField JT_P_DTS_Cari;
    private javax.swing.JTextField JT_P_T_Cari;
    private javax.swing.JTextField JT_P_U_ID_User;
    private javax.swing.JTextField JT_P_U_Nama_User;
    private javax.swing.JTextField JT_P_U_Telepon;
    private javax.swing.JTextField JT_P_U_Tempat_lahir;
    private javax.swing.JPanel Laporan;
    private javax.swing.JLabel Nama_User;
    private javax.swing.JPanel Service;
    private javax.swing.JLabel Tanggal;
    private javax.swing.JPanel Transaksi;
    private javax.swing.JPanel Transaksi_service;
    private javax.swing.JPanel User;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
